[phases.setup]
nixPkgs = [
  "python3",
  "gcc",
  "cmake",
  "lapack",
  "openblas",
  "xorg.libX11",
  "libglib",
  "libpng",
  "libjpeg",
  "zlib",
  "libxext",
  "libsm",
  "libice"
]

[phases.install]
nixEnvVars = { DLIB_USE_CUDA = "0", USE_AVX_INSTRUCTIONS = "1" }
