[phases.setup]
nixPkgs = [
  "python3",
  "gcc",
  "cmake",
  "lapack",
  "openblas",
  "xorg.libX11",
  "glib",
  "libpng",
  "libjpeg",
  "zlib",
  "xorg.libXext",
  "xorg.libSM",
  "xorg.libICE"
]

[phases.install]
nixEnvVars = { DLIB_USE_CUDA = "0", USE_AVX_INSTRUCTIONS = "1" }
